import { ListInfo } from './ListInfo';

// Mock数据
export const MEMO_DATA: ListInfo[] = [
  new ListInfo($r("app.media.list_exchange_ic_public_cards_filled"), '账户余额'),
  new ListInfo($r("app.media.list_exchange_ic_public_cards_filled2"), 'xx银行储蓄卡（1234）'),
  new ListInfo($r("app.media.list_exchange_ic_public_cards_filled3"), 'xx银行储蓄卡（1238）'),
  new ListInfo($r("app.media.list_exchange_ic_public_cards_filled4"), 'xx银行储蓄卡（1236）')
];