import { HSIAdvModel } from "@learn/adv_har";

export const ARTICLE_DATA: HSIAdvModel[] = [
  {id:"art_id",interType:0,title:"调试link",url:"",linkUrl:"hslearn://abc/"},
  {
    id:"art_id",
    interType: 1,
    title: 'HarmonyOS NEXT应用开发性能优化入门引导',
    url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/README.md',
  },
  {
    id:"art_id",
    interType: 1,
    title: '性能优化实操宝典',
    url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/performance-optimization-practical-guidance.md',
  },
  {
    id:"art_id",
    interType: 2,
    title: 'ArkTS高性能编程',
    items: [
      {
        id:"art_id",
        interType: 1,
        title: '高性能编程规范',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/high-performance-programming.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '高效并发编程',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/efficient-concurrent-programming.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: 'N-API高效开发指导',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/develop-Native-modules-using-NAPI-safely-and-efficiently.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '多线程能力场景化',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/multi_thread_capability.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '利用native的方式实现跨线程调用',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/native-threads-call-js.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '避免开发过程中的冗余操作',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/avoiding-redundant-operations.md'
      }
    ]
  },
  {
    id:"art_id",
    interType: 2,
    title: '减少卡顿丢帧',
    items: [
      {
        id:"art_id",
        interType: 1,
        title: '正确使用LazyForEach优化',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/lazyforeach_optimization.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '组件复用使用指导',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/component-recycle.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '组件复用四板斧',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/component_recycle_case.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '组件复用总览',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/component-reuse-overview.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: 'WaterFlow高性能开发指导',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/waterflow_optimization.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: 'Swiper高性能开发指导',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/swiper_optimization.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理进行状态管理',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/proper_state_management.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '精准控制组件的更新范围',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/precisely-control-render-scope.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理使用renderGroup',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/reasonable-using-renderGroup.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理使用多线程共享内存',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/thread_memory_shared.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: 'Grid高性能开发指导',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/grid_optimization.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '状态管理优秀实践',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/arkts-state-management-best-practices.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理使用renderGroup',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/reasonable-using-renderGroup.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理处理高负载组件的渲染',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/reasonably-dispose-highly-loaded-component-render.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理使用自定义组件冻结功能',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/custom_component_freeze.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '避免在滑动场景的高频回调接口中处理耗时操作',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/avoid_high_frequency_callback_execute_lengthy_operation.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理使用renderGroup',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/reasonable-using-renderGroup.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '避免在主线程中执行耗时操作',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/avoid_time_consuming_operations_in_mainthread.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '避免在主线程中执行耗时操作',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/avoid_time_consuming_operations_in_mainthread.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理使用系统接口',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/reasonable_using_system_interfaces.md'
      }
    ]
  },
  {
    id:"art_id",
    interType: 2,
    title: '提升应用启动和响应速度',
    items: [
      {
        id:"art_id",
        interType: 1,
        title: '提升应用冷启动速度',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/improve-application-cold-start-speed.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '提升应用响应速度',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/improve-application-response.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: 'Flex布局性能提升使用指导',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/flex-development-performance-boost.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '优化布局性能',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/reduce-view-nesting-levels.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理选择条件渲染和显隐控制',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/proper-choice-between-if-and-visibility.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理使用IPC通信',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/reasonable-using-ipc.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理进行状态管理',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/reasonable-using-ipc.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '文件上传下载性能提升指导',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/improve-file-upload-and-download-performance.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '减少首帧绘制时的冗余操作',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/reduce-redundant-operations-when-render-first-frame.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理使用多线程共享内存',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/thread_memory_shared.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '动效能力实践',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/animation_practice.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '性能提升的其他方法',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/arkts-performance-improvement-recommendation.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理使用renderGroup',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/reasonable-using-renderGroup.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '运行时动态加载页面提升性能',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/performance-dynamic-import.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '合理运行后台任务',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/reasonable-running-backgroundTask.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: 'Web组件开发性能提升指导',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/performance-web-import.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '使用同层渲染在Web上渲染原生组件',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/webview-render-app-components.md'
      },
      {
        id:"art_id",
        interType: 1,
        title: '全局自定义组件复用实现',
        url: 'https://gitee.com/harmonyos-cases/cases/blob/master/docs/performance/node_custom_component_reusable_pool.md'
      }
    ]
  }
]