export { MainPage } from './src/main/ets/components/mainpage/MainPage'

export { axiosInstance, IApiResponse, IApiResultData, IApiParams, IApiBodyData, apiRequest, ApiRequestType, axiosAddHeader} from './src/main/ets/AxiosRequest/AxiosRequest'
export { getUserApi,axiosCommonApi} from './src/main/ets/AxiosRequest/commonaApis'

//网络请求
export { API } from './src/main/ets/core/API';
export { NetCallback } from './src/main/ets/core/NetCallback';
export { NetMagicResp } from './src/main/ets/core/NetMagicResp';
export { netReq } from './src/main/ets/core/NetRequest';