
export class YWResColor {
  static themeLight(): ResourceColor {
    return $r('app.color.theme_light')
  }

  static themeDefault(): ResourceColor {
    return $r('app.color.theme_default')
  }

  static themeUnselect(): ResourceColor {
    return $r('app.color.theme_unselect')
  }

  static themeColor(): ResourceColor {
    return $r("app.color.col_0D0D0D")
  }

  static tabNormalColor(): ResourceColor {
    return $r("app.color.col_999999")
  }


  static bgBase(): ResourceColor {
    return $r('app.color.bg_base')
  }

  static title(): ResourceColor {
    return $r('app.color.title')
  }

  static main(): ResourceColor {
    return $r('app.color.main')
  }

  static desc(): ResourceColor {
    return $r('app.color.desc')
  }
}