export class YWResImage {
  static appIcon(): Resource {
    return $r('app.media.app_icon');
  }

  static tab_home(): Resource {
    return $r('app.media.tab_home_normal')
  }

  static tab_home_h(): Resource {
    return $r('app.media.tab_home_select')
  }

  static tab_category(): Resource {
    return $r('app.media.category_normal')
  }

  static tab_category_h(): Resource {
    return $r('app.media.category_select')
  }

  static tab_car(): Resource {
    return $r('app.media.tab_bag_normal')
  }

  static tab_car_h(): Resource {
    return $r('app.media.tab_bag_select')
  }

  static tab_mine(): Resource {
    return $r('app.media.tab_me_normal')
  }

  static tab_mine_h(): Resource {
    return $r('app.media.tab_me_select')
  }

  static arrowLeftIcon(): Resource {
    return $r('app.media.arrow_left')
  }

  static arrowRightIcon(): Resource {
    return $r('app.media.arrow_right')
  }

  static whiteArr(): Resource {
    return $r('app.media.white_arr')
  }

  static userAvatar(): Resource {
    return $r('app.media.user_avatar')
  }

  static defaultPlaceholder(): Resource {
    return $r('app.media.placeholder')
  }

  static backArrow(): Resource {
    return $r('app.media.tab_bag_normal') //todo 返回按钮
  }

  static delete(): Resource {
    return $r('app.media.delete')
  }

  static edit(): Resource {
    return $r('app.media.edit')
  }

  //car
  static cartHelp(): Resource {
    return $r('app.media.cartHelp')
  }

  static addressArr(): Resource {
    return $r('app.media.address_arr')
  }

  static addressCheckMark(): Resource {
    return $r('app.media.address_check_mark')
  }

  static addressClose(): Resource {
    return $r('app.media.address_close')
  }

  static addressCompany(): Resource {
    return $r('app.media.address_company')
  }

  static cartSaleEn(): Resource {
    return $r('app.media.cart_sale_en')
  }

  //勾选
  static checkBox(): Resource {
    return $r('app.media.checkbox')
  }

  static checkBoxGray(): Resource {
    return $r('app.media.checkbox_gray')
  }

  //定位
  static addressLocate(): Resource {
    return $r('app.media.address_locate')
  }

  static addressMap(): Resource {
    return $r('app.media.address_map')
  }
  //空白
  static bankData(): Resource {
    return $r('app.media.recently_data_bank')
  }

  static orderBank(): Resource {
    return $r('app.media.order_bank')
  }
}