
export class YWResFloat {
  static fontTitle(): Resource {
    return $r('app.float.font_title')
  }

  static fontMain(): Resource {
    return $r('app.float.font_main')
  }

  static fontDesc(): Resource {
    return $r('app.float.font_desc')
  }

  static fontSmart(): Resource {
    return $r('app.float.font_desc_smart')
  }

  static fontTag(): Resource {
    return $r('app.float.font_tag')
  }
}