
export class YWResString {
  static appName(): ResourceStr {
    return $r('app.string.app_name')
  }
  static mainHome(): ResourceStr {
    return $r('app.string.main_home')
  }
  static mainCategory(): ResourceStr {
    return $r('app.string.main_category')
  }
  static mainCar(): ResourceStr {
    return $r('app.string.main_car')
  }
  static mainMine(): ResourceStr {
    return $r('app.string.main_mine')
  }
}