
export class YWResColor {
  static themeLight(): ResourceColor {
    return $r('app.color.theme_light')
  }

  static themeDefault(): ResourceColor {
    return $r('app.color.theme_default')
  }

  static themeUnselect(): ResourceColor {
    return $r('app.color.theme_unselect')
  }

  static bgBase(): ResourceColor {
    return $r('app.color.bg_base')
  }

  static title(): ResourceColor {
    return $r('app.color.title')
  }

  static main(): ResourceColor {
    return $r('app.color.main')
  }

  static desc(): ResourceColor {
    return $r('app.color.desc')
  }
}