
export const BASE_URL = 'https://www.wanandroid.com';

export const USER_REGISTER ='user/register';

export const USER_LOGIN ='user/login';

export const GET_BANNER ='/banner/json';

export const GET_NEWS ='/article/list';

export const HOT_KEY ='/hotkey/json';

export const QUERY_KEY ='/article/query/0/json';


export  const QUERY_INTEGRAL='//lg/coin/list'


export  const  QUERY_RANK='/lg/coin/userinfo/json'

export const  QUERY_ARTICLE='/user_article/list/0/json'

export const  ADD_ARTICLE="/lg/user_article/add/json"


export const  QUERY_CLASSIFY='/wxarticle/chapters/json'



export  const  QUERY_HISTORY='/wxarticle/list/'





