export enum YWNavPath {

  root_old_test_demo = "learn://root/root_old_test_demo",

  root = "learn://root/learn",
  root_main_nav = "learn://root/main_nav",
  root_setting = "learn://root/set_har/setting",
  root_login = "learn://root/login_har/login",

  main_tab_nav = "learn://root/main_tab_nav",

  main_tab_content_anv = "learn://root/main_tab_nav/content",

  main_tab_home = "learn://root/main_tab_nav/Home",
  main_tab_category = "learn://root/main_tab_nav/CATEGORY",
  main_tab_car = "learn://root/main_tab_nav/CAR",
  main_tab_mine = "learn://root/main_tab_nav/MINE",

  vc_car = "learn://vc/car",

  common_tab_nav = "learn://root/common_tab_nav",

  root_lion_nav = "learn://root/lion_nav",
  root_lion_tab_nav = "learn://root/lion_tab_nav",

  lion_tab_home = "learn://root/lion_tab_home",
  lion_tab_news = "learn://root/lion_tab_news",
  lion_tab_me = "learn://root/lion_tab_me",

  //
  root_demo_tab_nav = "learn://root/demo_tab_nav",


}